name: EssentialsS
main: com.salkcoding.essentialss.EssentialsS
version: 1.1.0-SNAPSHOT
description: Essentials by Salk_Coding
api-version: 1.16
author: Salk_Coding
depend: [ KotlinBukkitAPI, BukkitLinked, Metamorphosis ]
commands:
  kickall:
    description: kickall
  list:
    description: list
  seen:
    description: seen
  tp:
    description: tp
  tpall:
    description: tpall
  tphere:
    description: tphere
  ci:
    description: clear inventory
    aliases: [clearinventory]
  feed:
    description: feed
  fly:
    description: fly
  gamemode:
    description: gamemode
    aliases: [gm]
  heal:
    description: heal
  killall:
    description: killall
  more:
    description: more
  near:
    description: near
  repair:
    description: repair
  speed:
    description: speed
  top:
    description: top
  tppos:
    description: tppos
  tpwpos:
    description: tpwpos
  xp:
    description: xp